name: Transcribe Audio

on:
  push:
    paths:
      - '**/*.wav'
      - '**/*.mp3'
      - '**/*.flac'

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-speech

    - name: Transcribe audio
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        python transcribe.py $AUDIO_FILE_PATH

    - name: Commit transcription
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add transcriptions/
        git commit -m 'Add transcription for $AUDIO_FILE_PATH'
        git push
